# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jaeyong Park
title: Computer Architecture & System Software Researcher
email: jypark9818@korea.ac.kr
website: https://comsys-lab.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: jypark9818
linkedin_username: jaeyong-park-3182a7204
orcid_username: 0009-0001-4373-3963

# About Section
about_title: About Jaeyong Park
about_profile_image: images/profile.jpg
about_content: | 
  I am a 3rd year integrated M.S/Ph.D course student at Korea University.  
  My research focuses on cost-efficient deep neural network (DNN) acceleration, exploring tiered memory systems, NPU architectures, and scalable memory solutions for future datacenter servers.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Super Awesome Project
        link: https://github.com/sproogen/modern-resume-theme
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/sproogen/modern-resume-theme
        quote: >
          One of the greatest apps ever created.
        description: |
          This project began as a journey to learn React and has evolved into a fully fledged app. It reflects my passion for creating innovative software solutions.
        
  - title: Publications
    layout: list
    content:
      - layout: left
        title: SAVector: Vectored Systolic Arrays
        quote: >
          A novel scale-out DNN inference accelerator architecture with vectored systolic arrays and a two-level on-chip buffer hierarchy.
        description: |
          This paper introduces SAVector, which overcomes the low utilization of scale-up architectures by employing multiple small systolic arrays. The proposed design leverages shared buffers and prefetching techniques to significantly reduce off-chip memory accesses and improve energy efficiency.
      - layout: left
        title: Concordia: Mitigating Software Overhead in Tiered Memory-Based Deep Learning Training System
        quote: >
          An innovative tiered memory system that minimizes redundant FTL operations for deep learning training.
        description: |
          Concordia addresses performance bottlenecks in flash-based memory systems by statically predicting data migration patterns and storing reusable FTL mappings. This approach reduces software overhead and achieves performance parity with DRAM-only configurations.
      - layout: left
        title: VitBit: Enhancing Embedded GPU Performance for AI Workloads through Register Operand Packing
        quote: >
          A software technique that boosts embedded GPU performance via register operand packing.
        description: |
          VitBit overcomes the limitations of fixed GPU numeric formats by enabling efficient processing of low-bit integer values. The method allows simultaneous use of Tensor, INT, and FP CUDA cores, thereby reducing execution time and improving arithmetic density on platforms like NVIDIA Jetson AGX Orin.
      - layout: left
        title: TM-Training: An Energy-Efficient Tiered Memory System for Deep Learning Training in NPUs
        quote: >
          A tiered memory system that optimizes data placement to reduce energy consumption in DNN training.
        description: |
          TM-Training proposes a proactive data placement strategy within a two-tier memory system (HBM DRAM and NAND Flash). By splitting tensors and scheduling data movements efficiently, the approach reduces inter-tier traffic and enhances training throughput per watt.
      - layout: left
        title: MOST: Memory Oversubscription-aware Scheduling for Tensor Migration on GPU Unified Storage
        quote: >
          A scheduling framework that mitigates memory oversubscription stalls in GPU unified storage.
        description: |
          MOST improves data migration in environments using Unified Virtual Memory by balancing pre-eviction and prefetching operations. This software framework reduces page fault stalls and speeds up DNN training compared to state-of-the-art techniques.
        
  - title: Experience
    layout: list
    content:
      - layout: left
        title: The Boring Company
        link: https://www.boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems with innovative network solutions.
        description: |
          At The Boring Company, I lead a team to maintain and advance the company's network infrastructure, driving adoption of cutting-edge technologies.
        
  - title: Education
    layout: list
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          One of the world's most prestigious institutions.
        description: |
          My time at Harvard honed my technical and collaborative skills. I actively participated in extracurricular activities like the Harvard Mountaineering Club, enriching my university experience.
        
  - title: A Little More About Me
    layout: text
    content: |
      Beyond my passion for computer architecture and system software, I enjoy:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
      
      Here's a cool image:
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
